### ISSUE TITLE
trd.py is crashing on market open

### ISSUE THREAD

**Issue by FifthHour** [FifthHour/kyth#42]

**Comment by FifthHour** [comment]
C:\Users\Administrator\fh\kyth\fhlib.py:222: RuntimeWarning: divide by zero encountered in double_scalars
  unittemp = (str_risk * acc_nav)/(price * sl_pcnt)/(home_price)
Traceback (most recent call last):
  File "trd.py", line 151, in <module>
    api_conn.order_create(acc[asd], units, tradeset.iloc[trade_row].instrument, tradeset.iloc[trade_row].order_type, ord_sl, ord_tp, ent_pr)
  File "C:\Users\Administrator\fh\kyth\fhlib.py", line 193, in order_create
    self.client.request(order_req)
  File "C:\ProgramData\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py", line 306, in request
    request_args, headers=headers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\oandapyV20\oandapyV20.py", line 243, in __request
    response.content.decode('utf-8'))
oandapyV20.exceptions.V20Error: {"errorMessage":"Invalid JSON, ParseErrorCode: 3, Message: Invalid value."}

**Comment by FifthHour** [comment]
issues comes from zero values in tradeset sl_bp, tp_bp and pend_bp
